### PR TITLE
feat: added contribution page

### LINKED ISSUE #9: Draft: Add contributing page
Users, developers or any other interested person or organization/ company can help us out via different methods. The below is to gather ideas and the required infromation to add into a "contributing" page or section.

I like the below blocks and would like similar blocks for the different contributing methods;
image

Below how the page could look like. First a bit of introductional text, followed by the different blocks underneath.

---

# How you can help
OpenVoiceOS is an open-source voice assistant platform powered by a passionate community of developers, translators, testers, and advocates. Whether you're skilled in coding, translation, testing, documentation, or simply spreading the word, your contributions are vital to our mission of creating a customizable, privacy-focused, and inclusive voice assistant. We're also grateful for financial donations, which help sustain the project's growth and innovation. No matter how you choose to contribute, your involvement helps make OpenVoiceOS a powerful, adaptable, and accessible tool for users around the world.

## Coding
OpenVoiceOS, is always actively seeking contributions from developers across its entire framework. Whether you're skilled in front-end interfaces, backend services, machine learning, or voice recognition, your expertise can help advance this community-driven project. Developers can contribute by improving existing features, fixing bugs, or optimizing performance, ensuring the platform remains robust, user-friendly, and accessible to a broader audience.

## Building a skill and/ or plugin
We welcome developers who can create skills and plugins to help expand its functionality and versatility. By contributing your creativity with coding new skills, enhance existing ones, or develop new plugins that integrate seamlessly with the platform we enrich the user experience and offering more personalized and diverse interactions.

## Helping with translation
OpenVoiceOS is committed to ensuring that no language is left behind and is seeking help from translators around the globe to make this vision a reality. As an open-source voice assistant platform, OpenVoiceOS aims to be accessible to users around the world, regardless of their native language.

## Testing & Quality Assurance
The easiest way to contribute is most likely by just user, test and report back any issues found for quality assurance. This helps to maintain the platform's reliability and performance, ensuring that the voice assistant functions work seamlessly across various devices and scenarios whic is crucial for delivering a top-notch user experience. Identifying and resolve bugs, improve system stability, and ensure that new features are implemented smoothly.

## Documentation
OpenVoiceOS is seeking contributors to help enhance both user and developer documentation, a critical aspect of making the platform accessible and easy to use. Clear, comprehensive documentation is essential for guiding users through the setup and operation of the voice assistant, as well as for assisting developers in creating new features, skills, and plugins. Whether you're skilled in writing, technical communication, or have a deep understanding of OpenVoiceOS, your contributions can ensure that documentation is thorough, up-to-date, and user-friendly.

## Sharing is Caring
We are looking for passionate advocates to help spread the word. By raising awareness through social media, blogs, community forums, and other channels, you can play a crucial role in growing the OpenVoiceOS community. Whether you enjoy creating content, engaging with tech enthusiasts, or networking within developer circles, your efforts can help attract more users and contributors to the project.

## Donating
OpenVoiceOS welcomes support in the form of donations to help sustain and grow its open-source voice assistant platform. Donations play a vital role in covering essential expenses, such as server costs, development tools, and other resources that keep the project running smoothly. By contributing financially, you can directly impact the platform's ability to innovate, improve, and remain accessible to everyone. Whether it's a one-time donation or ongoing support, every contribution helps ensure that OpenVoiceOS continues to thrive as a community-driven project

### PR DESCRIPTION
**Pull request by suvanbanerjee**
Screenshot from 2024-08-10 13-24-42

Screenshot from 2024-08-10 13-24-19

Screenshot from 2024-08-10 13-24-28

Screenshot from 2024-08-10 13-24-24

Screenshot from 2024-08-10 13-24-37

Closes #9 

@j1nx the only thing remaining is the url for each subsection

## Summary by CodeRabbit

- **New Features**
	- Introduced a dedicated "Contribute" page to guide users on how to contribute to the project.
	- Added a "Contributions" component outlining various ways users can get involved, including coding, documentation, and financial support.
	- Implemented a "Donate" page featuring various donation methods to support the project.
	- Created a "Share" component to encourage users to promote the OpenVoiceOS platform through different channels.
- **Style**
	- Enhanced visual consistency in the "Hero" component by updating the link colors for dark mode, improving accessibility and user experience.

### CODE REVIEW

**Comment by j1nx** [comment]
## Coding link
https://openvoiceos.github.io/ovos-technical-manual/community/

## Skills & Plugin link
https://openvoiceos.github.io/ovos-technical-manual/guidelines/

## Translating link
https://www.openvoiceos.org/translation

## Documentation link
https://ovos-user-manual.openvoiceos.org/

## Testing and Quality Assurance link
https://github.com/orgs/OpenVoiceOS/discussions/categories/q-a

## Sharing is caring link
(page to be written)

## Donating
See additional page / content below

**Comment by j1nx** [comment]
Hereby my first version of the "Donation link page" to be added and linked to. I can and will update the different methods with links onces they become available and are live. This just a first version, we can always add (or remove) methods if needed.

---
# Donating to OpenVoiceOS
OpenVoiceOS is an open-source project that relies on community support to continue development. If you'd like to contribute, there are several ways you can do so:

## PayPal
Donate via PayPal for a one-time contribution or set up a recurring donation. This option provides the flexibility to choose the amount you want to give.

## Patreon
Support us on Patreon and gain access to exclusive content, updates, and rewards based on your subscription tier. Patreon allows for monthly recurring donations, perfect for ongoing support.

## Liberapay
Liberapay is a platform for recurring donations with no fees for the donor. You can set up a weekly, monthly, or yearly donation to support our continuous efforts.

## GitHub Sponsor
If you're active on GitHub, you can sponsor OpenVoiceOS directly through GitHub Sponsors. Choose a sponsorship tier that fits your budget and support us directly on the platform.

## How Your Donation Helps
Your donations are crucial in sustaining the OpenVoiceOS project. The funds are used to facilitate software development, acquire and test hardware, maintain infrastructure, and promote the project to reach a broader audience. Additionally, donations help cover the costs of providing user support and ensuring the platform's continuous improvement. Every contribution, no matter the size, plays a significant role in keeping OpenVoiceOS thriving and evolving.

**Comment by j1nx** [comment]
And the "sharing is caring" webpage to be added and linked to;

---

# Share OpenVoiceOS with the World
Whether you're a developer, tech enthusiast, vlogger, blogger or just someone passionate about digital freedom, OVOS offers a powerful platform for voice-controlled technology that respects your privacy and puts you in control and the world needs to know!

## How You Can Spread the Word

1. Talk About It
Start by sharing your excitement for OpenVoiceOS with friends, family, and colleagues. Discuss the benefits of an open-source, privacy-first voice platform and how it empowers users to take control of their technology.

2. Share on Social Media
Use your social media platforms to share updates, features, and personal experiences with OVOS. Don’t forget to tag us and use the hashtag #OpenVoiceOS to connect with others who are passionate about the project.

3. Write a Blog Post or Article
If you have a blog or write for a tech publication, consider writing a post about your experiences with OVOS. Share tips, tutorials, or insights on why OVOS is a game-changer in the voice technology space.

4. Create Content
Videos, podcasts, and live streams are great ways to engage your audience. Whether it’s a tutorial, a review, or a deep dive into OVOS features, your content can help others discover the project and understand its potential.

## Why Your Voice Matters?
Sharing OpenVoiceOS with the world not only helps grow the community but also promotes the values of open-source software and privacy. By talking about OVOS, you’re advocating for a future where users have more control over their technology and data.

Let’s build something amazing together. Share OpenVoiceOS today!

**Review by j1nx — CHANGES_REQUESTED** [review]
I added webpage content for the donations page and the sharing page. @suvanbanerjee If you could please be so kind to add those two pages as well and link to them from this page together with the other proviced links, that would be great.

7 blocks is not the nicest to scale, so I would like to propose to remove the "Quality Assurance" block for now, so we end up with two rows of three blocks.

Let me know if you have any questions, comments or suggestions.

**Comment by suvanbanerjee** [comment]
@j1nx By today EOD (IST) i will make all changes and merge

**Pull request merged**
